"""initial_schema

Revision ID: 6ab614fd4219
Revises: 
Create Date: 2025-12-31 12:39:16.903568

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab614fd4219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('goal', sa.Enum('WEIGHT_LOSS', 'MUSCLE_GAIN', 'FLEXIBILITY', 'ENDURANCE', 'GENERAL_FITNESS', 'REHAB_MOBILITY', name='programgoal'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('equipment_needed', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('minutes_per_session', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_programs_difficulty', 'programs', ['difficulty'], unique=False)
    op.create_index('ix_programs_featured', 'programs', ['is_featured', 'is_published'], unique=False)
    op.create_index('ix_programs_goal', 'programs', ['goal'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('privacy_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('data_processing_consent', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_user_purpose', 'otp_codes', ['user_id', 'purpose'], unique=False)
    op.create_table('program_enrollments',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('program_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_workouts_completed', sa.Integer(), nullable=False),
    sa.Column('total_minutes_completed', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_workout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_enrollment_user_program')
    )
    op.create_index('ix_enrollments_user_active', 'program_enrollments', ['user_id', 'is_active'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('fitness_level', sa.String(length=20), nullable=True),
    sa.Column('primary_goal', sa.String(length=50), nullable=True),
    sa.Column('secondary_goals', sa.Text(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('minutes_per_session', sa.Integer(), nullable=True),
    sa.Column('preferred_days', sa.Text(), nullable=True),
    sa.Column('injuries', sa.Text(), nullable=True),
    sa.Column('equipment_available', sa.Text(), nullable=True),
    sa.Column('workout_location', sa.String(length=20), nullable=True),
    sa.Column('prefers_cardio', sa.Boolean(), nullable=True),
    sa.Column('prefers_strength', sa.Boolean(), nullable=True),
    sa.Column('interested_in_yoga', sa.Boolean(), nullable=True),
    sa.Column('health_disclaimer_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workouts',
    sa.Column('program_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='intensitylevel'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('video_title', sa.String(length=200), nullable=True),
    sa.Column('video_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('calories_estimate', sa.Integer(), nullable=True),
    sa.Column('equipment_needed', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'day_number', name='uq_workout_program_day')
    )
    op.create_index('ix_workouts_program', 'workouts', ['program_id'], unique=False)
    op.create_table('workout_completions',
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workout_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('difficulty_felt', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['program_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'workout_id', name='uq_completion_enrollment_workout')
    )
    op.create_index('ix_completions_enrollment', 'workout_completions', ['enrollment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_completions_enrollment', table_name='workout_completions')
    op.drop_table('workout_completions')
    op.drop_index('ix_workouts_program', table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('user_profiles')
    op.drop_index('ix_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_enrollments_user_active', table_name='program_enrollments')
    op.drop_table('program_enrollments')
    op.drop_index('ix_otp_user_purpose', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_programs_goal', table_name='programs')
    op.drop_index('ix_programs_featured', table_name='programs')
    op.drop_index('ix_programs_difficulty', table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###


